### ISSUE TITLE
Project’s Card | Auto Scrolling Flow

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rf5#6]
As a user I, when I collapse/expand any section in the project card, I expect the other card will do an auto-scroll to that section, so I can compare the context of those sections more easily. 

**Success Criteria:**

- [x] Auto-Scroll the other card while expanding/collapsing the main sections

**Comment by maryjaf** [comment]
It seems[ this problem](https://github.com/GeneralMagicio/pairwise-rpgf5/issues/5#issuecomment-2367765396) is related to this issue @mmahdigh  

https://github.com/user-attachments/assets/b31da5ce-d29b-496d-8a9f-3b8107e4daab

**Comment by maryjaf** [comment]
> It seems[ this problem](https://github.com/GeneralMagicio/pairwise-rpgf5/issues/5#issuecomment-2367765396) is related to this issue @mmahdigh
> 
>  Screen.Recording.2024-09-26.at.10.42.58.AM.mov

Yeah @mmahdigh I reported this problem on this issue again, I thought maybe it's related to auto scrolling

**Comment by mmahdigh** [comment]
> > It seems[ this problem](https://github.com/GeneralMagicio/pairwise-rpgf5/issues/5#issuecomment-2367765396) is related to this issue @mmahdigh
> > Screen.Recording.2024-09-26.at.10.42.58.AM.mov
> 
> Yeah @mmahdigh I reported this problem on this issue again, I thought maybe it's related to auto scrolling

Thanks! Found the bug. It's fixed on staging.

**Comment by maryjaf** [comment]
> Yeah @mmahdigh I reported this problem on this issue again, I thought maybe it's related to auto scrolling

This problem has been fixed
